
services:
  slack-n8n-websocket-proxy:
    container_name: slack-n8n-websocket-proxy
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SLACK_APP_TOKEN
      - SLACK_BOT_TOKEN
      - N8N_WEBHOOK_URL
